name: C Kompilace Test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Stáhnout kód z repozitáře
      uses: actions/checkout@v4

    - name: Ověřit instalaci GCC
      run: gcc --version

    - name: Compilation of main.c
      run: gcc main.c -o wordlist_profiler
